### ISSUE TITLE
Bcftools mpileup error

### ISSUE THREAD

**Issue by Tarun-PAU** [YuSugihara/QTL-seq#47]
please suggest, how to rectify this error.

[QTL-seq:2024-02-09 21:00:33] !!ERROR!! bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r LR618874.1 -f tarunm/10_ref/maize.fa --ignore-RG tarunm/20_bam/parent.bam tarunm/20_bam/bulk1.bam tarunm/20_bam/bulk2.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o tarunm/30_vcf/qtlseq.LR618874.1.vcf.gz >> tarunm/log/bcftools.LR618874.1.log 2>&1

**Comment by YuSugihara** [comment]
Thank you very much for reporting the error, and I'm sorry for the late response.

I have actually found an error similar to this one in some specific environments.
We have modified the scripts to avoid this error since MutMap v2.3.5 and QTL-seq v2.2.5 were released.
Therefore, please try the latest version of QTL-seq.

I will write down what I observed in the previous version here to help people who have encountered the same error.

1/ This error occurred when VCF files were generated in parallel via Python multiprocessing.

2/ This error was not observed in the test dataset (https://github.com/YuSugihara/QTL-seq/tree/master/test) which was created with a single chromosome.

3/ In the log files for bcftools, you can see an error log like the one below:
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable

**4/ This error was resolved by exporting the environmental variables OMP_NUM_THREADS=8 and USE_SIMPLE_THREADED_LEVEL3=8.
You can set the number of threads to be the same as the number defined in the QTL-seq option.**
